### ISSUE TITLE
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://188.120.239.162:8841/api/sendTransaction` resulted in a `500 Internal Server Error` response: {"code":106,"log":"Check tx error: incorrect tx signature"}

### ISSUE THREAD

**Issue by vanlikk** [MinterTeam/minter-php-sdk#14]
Код скрипта: https://pastebin.com/RLn3AFAS
Полный стектрейс прогона скрипта: https://pastebin.com/ZEiHZySr

Последовательно выполняется отправка транзакций с одного фиксированного адреса на другой, но на 49ой итерации скрипт валится с ошибкой: 

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://188.120.239.162:8841/api/sendTransaction` resulted in a `500 Internal Server Error` response:
{"code":106,"log":"Check tx error: incorrect tx signature"}

 in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
[root@mintervalidator src]#


```

@icoppupy

**Comment by GrKamil** [comment]
Не получается воспроизвести ошибку по Вашему коду.

**Comment by vanlikk** [comment]
Какие данные необходимы будут для лога, чтобы исследовать проблему? я бы добавил в прогрмму еще данных. Я сейчас установил новую версию, которая вышла сегодня. пока этой баги не встречал. Зато встретил нечто новое https://github.com/MinterTeam/minter-php-sdk/issues/17

**Comment by vanlikk** [comment]
Полностью снес minter-php и склонировал опять. Уже около 600 транзакций выполнено скриптом без ошибок. Бага не воспроизводится.
