### ISSUE TITLE
{"code":107,"log":"Check tx error: Insufficient funds for sender account: Mx0000000000000000000000000000000000000000. Wa (truncated...)

### ISSUE THREAD

**Issue by vanlikk** [MinterTeam/minter-php-sdk#15]
Код скрипта: https://pastebin.com/fW7PbFPF
Полный стектрейс прогона: https://pastebin.com/314pLD9L

Даже после апдейта библиотеки:
```
[root@mintervalidator src]# ~/composer.phar update
No composer.json in current directory, do you want to use the one at /root/minte                                                                                                             r-php-sdk? [Y,n]? y
Do not run Composer as root/super user! See https://getcomposer.org/root for det                                                                                                             ails
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating minter/minter-php-bip-44 dev-master (0c69093 => 9beecb5):  Checking out 9beecb5339
Writing lock file
Generating autoload files

```
все равно вылезает ошибка "Insufficient funds for sender account: Mx0000000000000000000000000000000000000000" после 17ой попытки провести транзакцию делегации: 
```
Try #:17
Date: Sun, 08 Jul 2018 20:31:02 +0300
array(4) {
  ["address"]=>
  string(42) "Mx80220bce4ce0c04d86cee4a7d8cdf26437a1ce19"
  ["private_key"]=>
  string(64) "7fa1dbb87e1cbfe8e335a484480b63746865418057342e87dea8730f7cf3d2d1"
  ["mnemonic"]=>
  string(73) "choice invest extend spider fat punch tackle buzz glad super sunset audit"
  ["seed"]=>
  string(128) "5a4b9e3b9f51d6e4e7a076c2d45642463db365dcce14c7d0d163cc8d3d132fe5aef30470a89b3b80680ca81c527fba5cca51577eed8ffefb977761b421da0790"
}
Sender: Mx0acdd852be6a2f9102cc6eff59c9383daa6db181
Sender Balance (MNT): 464066266657693577680
Receiver: Mx80220bce4ce0c04d86cee4a7d8cdf26437a1ce19
Fee between accounts: 100000000000
TX signed: f8758201670101aae98a4d4e54000000000000009480220bce4ce0c04d86cee4a7d8cdf26437a1ce19880de0bfcbf5d6a00080801ba094bf2d2b86df76b454156c48b4eea841002f304c528123af32ae221a9080eda7a007a483ad2280e6a722f084b186a39ec4ad9bdc9eea410d834badd501e32fb44c
Transaction Code: 0; TransactionResult: Mt18356494490eaa3b7d3ca601aeac468fd758cbd5
Delegation:
Delegate Balance (MNT): 1000010000000000000
Delegation Fee: 1000000000000
TX signed: f87f010105b6f5a0443269f55ceff73fbede50a4139f533f27397e80dbdd3ba0a0faf27dfa86bba18a4d4e5400000000000000880de0b6b3a764000080801ba037984172c285f706d27fa3fab1c7a0163d2342e656c30dceb5ab2004a0631344a00033b073ae5b35921338444d286c1ffb2f85c58164fa287c4eb10dfc6f9b2206
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://188.120.239.162:8841/api/sendTransaction` resulted in a `500 Internal Server Error` response:
{"code":107,"log":"Check tx error: Insufficient funds for sender account: Mx0000000000000000000000000000000000000000. Wa (truncated...)
 in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{cl in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
Try #:17
Date: Sun, 08 Jul 2018 20:31:02 +0300
array(4) {
  ["address"]=>
  string(42) "Mx80220bce4ce0c04d86cee4a7d8cdf26437a1ce19"
  ["private_key"]=>
  string(64) "7fa1dbb87e1cbfe8e335a484480b63746865418057342e87dea8730f7cf3d2d1"
  ["mnemonic"]=>
  string(73) "choice invest extend spider fat punch tackle buzz glad super sunset audit"
  ["seed"]=>
  string(128) "5a4b9e3b9f51d6e4e7a076c2d45642463db365dcce14c7d0d163cc8d3d132fe5aef30470a89b3b80680ca81c527fba5cca51577eed8ffefb977761b421da0790"
}
Sender: Mx0acdd852be6a2f9102cc6eff59c9383daa6db181
Sender Balance (MNT): 464066266657693577680
Receiver: Mx80220bce4ce0c04d86cee4a7d8cdf26437a1ce19
Fee between accounts: 100000000000
TX signed: f8758201670101aae98a4d4e54000000000000009480220bce4ce0c04d86cee4a7d8cdf26437a1ce19880de0bfcbf5d6a00080801ba094bf2d2b86df76b454156c48b4eea841002f304c528123af32ae221a9080eda7a007a483ad2280e6a722f084b186a39ec4ad9bdc9eea410d834badd501e32fb44c
Transaction Code: 0; TransactionResult: Mt18356494490eaa3b7d3ca601aeac468fd758cbd5
Delegation:
Delegate Balance (MNT): 1000010000000000000
Delegation Fee: 1000000000000
TX signed: f87f010105b6f5a0443269f55ceff73fbede50a4139f533f27397e80dbdd3ba0a0faf27dfa86bba18a4d4e5400000000000000880de0b6b3a764000080801ba037984172c285f706d27fa3fab1c7a0163d2342e656c30dceb5ab2004a0631344a00033b073ae5b35921338444d286c1ffb2f85c58164fa287c4eb10dfc6f9b2206
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://188.120.239.162:8841/api/sendTransaction` resulted in a `500 Internal Server Error` response:
{"code":107,"log":"Check tx error: Insufficient funds for sender account: Mx0000000000000000000000000000000000000000. Wa (truncated...)
 in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{cl in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

```
@icopuppy

**Comment by GrKamil** [comment]
Ошибку неправильной подписью поправили, спасибо.
