### ISSUE TITLE
Check tx error: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (transact (truncated...)

### ISSUE THREAD

**Issue by vanlikk** [MinterTeam/minter-php-sdk#17]
На 60ой транзакции все упало. Нода была проапдейчена на последний релиз (выпущен 16го июля):
```
Try #:60
Date: Tue, 17 Jul 2018 00:15:11 +0300
Sender: Mx0a46253f2256d6b2e2872e0682eb86d8fb20789f
Sender Balance (MNT): 34799940000000000000
Receiver: Mx08c75328b314c70121ebb5966718c3be822b70d0
TX signed: f8703d0101a7e68a4d4e54000000000000009408c75328b314c70121ebb5966718c3be822b70d085e8d4a5100080801ba000643d4deb93177e2366a71a3a0330afbbcc93231e91aef0652b6fdcc7fdf300a0444eb2b62353e949ece5e47c8d97c2a3246db3f592f4e9512dae80a1a4b55bfb
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://188.120.239.162:8841/api/sendTransaction` resulted in a `500 Internal Server Error` response:
{"code":106,"log":"Check tx error: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (transact (truncated...)
 in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{cl in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```
Код программы: https://pastebin.com/Vm0msuz6
Полный лог прогона программы сформированный скриптом: https://pastebin.com/8yiwNM7t 
Лог из докер docker logs minter-go-node_minter_1 : https://pastebin.com/nqg5KUmb
Лог из docker logs minter-go-node_tendermint_1 https://www.dropbox.com/s/00iq97jioa8jizj/log.txt?dl=0

**Comment by vanlikk** [comment]
Полностью снес minter-php и склонировал опять. Уже около 600 транзакций выполнено скриптом без ошибок. Бага не воспроизводится.
