### ISSUE TITLE
Перестал работать метод по делегированию монет мастерноде

### ISSUE THREAD

**Issue by vanlikk** [MinterTeam/minter-php-sdk#19]
Код, которым на предыдущей версии удалось делегировать 1000 кошельков мастерноде сейчас перестал работать. Падает при первой попытке. из того что было изменено: 
1. Отправитель
2. Public key
3. размер отправляемого стека. 

Валится именно на этапе делегирования. из того, что я вижу в изменениях API , там была изменена комиссия и номер типа транзакции. 

Код программы: https://pastebin.com/iTrSzPiP 

Ошибка: 
```
Try #:0
Date: Tue, 17 Jul 2018 01:48:30 +0300
array(4) {
  ["address"]=>
  string(42) "Mxc3ffe237c7838370183402e70fcf748a0b320a39"
  ["private_key"]=>
  string(64) "92412dd62a05a755a135efdf4cff909bae9dc0761724c9a4eca9aa041e04f55f"
  ["mnemonic"]=>
  string(72) "clump lens move east fossil deal strong teach tower slender utility left"
  ["seed"]=>
  string(128) "66c9b3a38e1bda8e8fe4244ed42241de75c569804a5b1eaa9655ac7e904e8a4266f7148a54e28a5f740ea6a52d62557ef2231a6ae3db723e240ffa0d0c502da1"
}
Sender: Mx0a46253f2256d6b2e2872e0682eb86d8fb20789f
Sender Balance (MNT): 46611850761710423123
Receiver: Mxc3ffe237c7838370183402e70fcf748a0b320a39
Fee between accounts: 100000000000
TX signed: f8734a0101aae98a4d4e540000000000000094c3ffe237c7838370183402e70fcf748a0b320a39881d24b2dfac52000080801ca0b623fa00cb0878effc0d41d3d72d45b2d5dfc8b7216446a49fee3c59a0be1d54a072c17c99da4bed3dd101a74a2e648b713218abde17d06484aef800fcff5f7213
Transaction Code: 0; TransactionResult: Mt3feb0b62ff405735211666678af5cfd082e9fdad
Delegation:
Delegate Balance (MNT): 2100000000000000000
Delegation Fee: 1000000000000
TX signed: f87f010105b6f5a0d7778450adafe7d4658494601b66e1a3020a4917b3a092a49386ee1d9bdb24a58a4d4e5400000000000000880de0b6b3a764000080801ba0f7bc52816fab87b10c8329287e1dfeeae8ddf5ac145cefde7d04ef4b0c643eaaa078d91b78353c1aedb8eb99ae17593a08acebbfdaf10151bde3f96a9f23d34973
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://188.120.239.162:8841/api/sendTransaction` resulted in a `500 Internal Server Error` response:
{"code":106,"log":"Check tx error: incorrect tx data"}

 in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(246) in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
[root@mintervalidator src]#

```

**Comment by vanlikk** [comment]
Просьба закрыть эту багу. Проблема была в том. что простой composer update не обновил все файлы, нужно было удалять minter-php и ставить заново. сейчас процесс пошел
