### ISSUE TITLE
Delegating coins: {"code":106,"log":"Check tx error: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (transact (truncated...)  in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

### ISSUE THREAD

**Issue by vanlikk** [MinterTeam/minter-php-sdk#21]
Очень редко появляется такая ошибка при делегации монет. может пройти 300 прогонов без ошибок, а может на 100ом свалиться:
```
Try #:146
Date: Fri, 27 Jul 2018 11:09:04 +0300
array(4) {
  ["address"]=>
  string(42) "Mxa90dfa4e400fcf0c7933d17c3b10cde4eb6b364b"
  ["private_key"]=>
  string(64) "4f20715bbb5b9a557ea108853c2d57f0784ed4be19aef427c4e49b0974740f1b"
  ["mnemonic"]=>
  string(73) "allow core soon family trouble initial sword oak romance treat awake much"
  ["seed"]=>
  string(128) "10678880521ed76d8eab49968d385780ed6e303d491fe586ea96ab678f832ae23f3126d91d2dae87e2f49c00f702ab296620ed95b4ceeadc54b851f8d006b0bd"
}
Sender: Mx0a46253f2256d6b2e2872e0682eb86d8fb20789f
Sender Balance (MNT): 981440129537174424934
Receiver: Mxa90dfa4e400fcf0c7933d17c3b10cde4eb6b364b
Fee between accounts: 10000000000000000
TX signed: f8808203cb018a4d4e540000000000000001aae98a4d4e540000000000000094a90dfa4e400fcf0c7933d17c3b10cde4eb6b364b880f43fc2c04ee000080801ca04fd60db4d4c0d64c6169e0809dc39a9c3d2046769a7185b1311cd7530f236796a0467da99a6db0df303065782ba763f2cb64bfbfe04b8465a18d14d5eb20bf31f3
Transaction Code: 0; TransactionResult: Mte8cfafa5f07aefdd73e60b022977d66d050f641e
Delegation:
Delegate Balance (MNT): 1100000000000000000
Delegation Fee: 100000000000000000
TX signed: f87901018a4d4e540000000000000007b6f5a0c6d5ebbf6092d31585cf365c8079b9e77a67fcd56c2f8084172c6d8634c6a83a8a4d4e5400000000000000880de0b6b3a764000080801ca086efc0693c33721c5d9ca690e3e3d6a2adbba95e961dec574e59c0fa43e58d658f000400000f00000000000000005700
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST http://188.120.239.162:8841/api/sendTransaction` resulted in a `500 Internal Server Error` response:
{"code":106,"log":"Check tx error: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (transact (truncated...)
 in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /root/minter-php-sdk/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{cl in /root/minter-php-sdk/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

```

Код программы https://pastebin.com/1wDyhPJY
Лог  прогона с 74 попытки: https://pastebin.com/6wNyTYYB 
@icopuppy

**Comment by GrKamil** [comment]
При последней версии SDK ?

**Comment by vanlikk** [comment]
Использовал версию, которая выходила неделю назад. в пятницу весь блокчейн лег, каких-то апдейтов я не ставил.
